### ISSUE TITLE
Calculating an indirect effect within a sequential mediation after bootstrapping

### ISSUE THREAD

**Issue by MarcLinderGit** [ISS-Analytics/seminr#249]
Dear seminr team,

First of all, I would like to thank you for the seminr package. I greatly appreciate your work and it fundamentally aids me in my research.

I would like to calculate the indirect effect within a sequential mediation after bootstrapping. Using the demo file as an example [demo("seminr-primer-chap7")], I basically would like to calculate the indirect effect of "COMP" through a first mediator "CUSA" then going through a seond mediator "LIKE" to "CUSL".

How could I obtain the effect size of this indirect effect from a seqential mediation analysis after bootstrapping?

Thanks in advance for any suggestion on this regard. Please find below my sample data and code:

# Load package
```{r}
library(seminr)
packageVersion('seminr')
```

# Load the data
```{r}
corp_rep_data <- corp_rep_data
```

# Create measurement model
```{r}
corp_rep_mm_ext <- constructs(
     composite("QUAL", multi_items("qual_", 1:8), weights = mode_B),
     composite("PERF", multi_items("perf_", 1:5), weights = mode_B),
     composite("CSOR", multi_items("csor_", 1:5), weights = mode_B),
     composite("ATTR", multi_items("attr_", 1:3), weights = mode_B),
     composite("COMP", multi_items("comp_", 1:3)),
     composite("LIKE", multi_items("like_", 1:3)),
     composite("CUSA", single_item("cusa")),
     composite("CUSL", multi_items("cusl_", 1:3))
   )
```

# Create structural model
```{r}
corp_rep_sm_ext <- relationships(
     paths(from = c("QUAL", "PERF", "CSOR", "ATTR"), to = c("COMP", "LIKE")),
     paths(from = c("COMP", "LIKE"), to = c("CUSA", "CUSL")),
     paths(from = c("CUSA"),         to = c("CUSL"))
   )
```

# Estimate the model
```{r}
corp_rep_pls_model_ext <- estimate_pls(
     data = corp_rep_data,
     measurement_model = corp_rep_mm_ext,
     structural_model  = corp_rep_sm_ext,
     missing = mean_replacement,
     missing_value = "-99")
```

# Extract the summary
```{r}
summary_corp_rep_ext <- summary(corp_rep_pls_model_ext)
```

# Bootstrap the model
```{r}
boot_corp_rep_ext <- bootstrap_model(
     seminr_model = corp_rep_pls_model_ext,
     nboot = 1000,
     cores = parallel::detectCores(),
     seed = 123)
```

# Summarize the results of the bootstrap
```{r}
summary_boot_corp_rep_ext <- summary(boot_corp_rep_ext, alpha = 0.05)
```

# Inspect total indirect effects
```{r}
summary_corp_rep_ext$total_indirect_effects
```

# Inspect indirect effects
```{r}
specific_effect_significance(boot_corp_rep_ext, from = "COMP", through = "CUSA", through = "LIKE", to = "CUSL", alpha = 0.05)
```

**Comment by soumyaray** [comment]
@LMM2021 @rondobohrens do let us know if the above suggestion solves the issue?
